settings:
  radius: 10 # Radius (blocks)
  time: 10 # Time (seconds)
  check-disabled-worlds: true # Check if world in BlackList (disabled-worlds)
  cooldown-time: 30 # CoolDown (seconds)
  cooldown-enabled: true # Issue CoolDown to those who do not have the right pleasantwallhack.bypass
messages:
  permission-required: '&aPleasantWallHack &8| &fYou do not have permission to perform this'
  world-disabled: '&aPleasantWallHack &8| &fWallHack disabled in this world'
  glow-enabled: '&aPleasantWallHack &8| &fHighlighted all players within the radius &a{radius} blocks&f for &a{time} sec.'
  nearby-players-empty: '&aPleasantWallHack &8| &fThere are no players near you.'
  cooldown: '&aPleasantWallHack &8| &fWait &a{time} sec. &funtil the next use of the command' 
disabled-worlds:
  - 'world_nether'
