name: PleasantWallHack
version: 1.1b
main: me.mstn.plugin.PleasantWallHack
depend: [ProtocolLib]
softdepend: [PlaceholderAPI]
authors: [Masston]
commands:
  PleasantWallHack:
    aliases: ["wh", "wallhack", "pwh"]